---
# ====== Application: apex-sample-app ========================
id: 102
identification: 
  name: apex-sample-app
  alias: APEX-SAMPLE-APP
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 21092930517748455

authorization: 
  authorization-scheme: Reader Rights # 21100136720748575
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: SN_DEV_6

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: apex-sample-app

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 120 Push Notifications Credentials # 21310797552764414

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 21093707806748465

navigation-bar: 
  implementation: List
  list: Navigation Bar # 21094777993748512
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 45909512617253

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: apex-sample-app

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 21088447327748434
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 45905885454656

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 21088727111748439
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 45905885454713

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 21089014064748440
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 45905885454737

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 21089291941748441
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 45905885454764

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 21089627393748442
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 45905885454789

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 21089922089748443
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 45905885454820

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 21090217264748444
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 45905885454844

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 21090503159748445
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 45905885454870

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 21090790371748446
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 45905885454901

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 21091109905748447
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 45905885454921

- # ====== Component Setting: NATIVE_IR ========================
  id: 21091412184748448
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 45905885454930

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 21091701585748449
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 45905885454959

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 21092008455748450
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 45905885454966

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 21092275922748451
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 45905885454969

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 21100978383748583
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 45905885457139

  configuration: 
    build-option: 'Feature: Feedback' # 21097535690748560

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 21101267897748584
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 45905885457241

  configuration: 
    build-option: 'Feature: Access Control' # 21097340566748560

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

